import { Poppins } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // font weights
  variable: "--font-poppins", // my CSS variable
});

export const metadata = {
  title: 'My Flight Site',
  description: 'Generated by Next.js',
  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className="font-poppins">
        {children}
        </body>
    </html>
  )
}
